### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by pc494** [pc494/onlineFDR#1]
- [ ] Update the CI so it includes Bioconductor testing
- [ ] Update the CI to auto-build the website
- [ ] Plan a versioning system
